name: Scheduled Data Generator # 工作流名称

on:
  # 设置定时任务触发器 (Cron表达式)
  schedule:
    # GitHub Actions 的时间基于 UTC。
    - cron: '0 8 * * 1-5'
  
  # 允许手动触发，方便测试
  workflow_dispatch: 

jobs:
  generate_and_commit:
    runs-on: ubuntu-latest # 使用 GitHub 提供的 Linux 虚拟机运行
    permissions:
        contents: write # 授予对仓库内容（文件）的写入权限
    steps:
      # 1. 检出代码 (必须，以便 Actions 能访问和修改文件)
      - name: Checkout Repository
        uses: actions/checkout@v4
        # 必须设置 fetch-depth: 0 以拉取完整历史，否则后续的提交可能会失败
        with:
          fetch-depth: 0

      # 2. 设置 Python 环境
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      # =======================================================
      # 关键步骤：创建 credentials 文件
      # =======================================================
      - name: Create Google Drive Credentials File
        # 使用 echo 命令将 Secret 变量的内容写入到 settings.yaml 文件中
        run: echo "${{ secrets.GDRIVE_CREDENTIALS_V2 }}" > settings.yaml
        shell: bash
      
      # =======================================================
      # 关键改进 1: 生成并使用今天的日期
      # =======================================================
      - name: Run Data Pipeline (Download, Process, Upload)
        # 使用 'date' 命令生成 YYYY-MM-DD 格式的字符串
        run: |
          TODAY_DATE=$(date +'%Y-%m-%d') 
          
          echo "今天的日期是: $TODAY_DATE"
          
          # install packages
          pip install -r requirements.txt

          # 执行你的 Python 脚本，将日期作为命令行参数传递
          python get_data.py --date=$TODAY_DATE --where=hk

          # 显示settings.yaml
          cat settings.yaml

          # 上传文件
          python upload_gdrive.py --date=$TODAY_DATE --where=hk
          